### ISSUE TITLE
502 [BUG]

### ISSUE THREAD

**Issue by arne182** [skrashevich/double-take#297]
**Version of Double Take**
`1.13.11.8`

**Expected behavior**
A clear and concise description of what you expected to happen. just work

**Screenshots**
![image](https://github.com/skrashevich/double-take/assets/844102/1f339fa1-0b9a-43b7-93c9-78dc9ebf2563)

**Hardware**
 - raspberry cm]
 - HA:
 - all
 

**Configuration**
# Double Take
# Learn more at https://github.com/jakowenko/double-take/#configuration
mqtt:
  host: ...
  username: ...
  password: ...
frigate:
  url: http://192.168.188.188:5000

detectors:
  deepstack:
    url: http://192.168.188.188

**Additional context**
Ever few minutes

**Comment by arne182** [comment]
21:15:21] debug: MQTT: subscribed to frigate/events, frigate/+/person/snapshot
[21:15:24] info: Access granted to IP address: ::ffff:172.30.32.2
[21:15:24] error: (node:63) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
[21:15:24] info: Access granted to IP address: ::ffff:172.30.32.2
[21:15:25] info: Access granted to IP address: ::ffff:172.30.32.2
[21:15:25] info: Access granted to IP address: ::ffff:172.30.32.2
[21:15:25] info: Access granted to IP address: ::ffff:172.30.32.2
[21:15:26] info: Access granted to IP address: ::ffff:172.30.32.2
[21:15:26] info: Access granted to IP address: ::ffff:172.30.32.2
[21:15:29] info: Access granted to IP address: ::ffff:172.30.32.2

**Comment by skrashevich** [comment]
it's known bug; already fixed in [v1.13.11.9rc2](https://github.com/skrashevich/double-take/releases/tag/v1.13.11.9rc2)

**Comment by arne182** [comment]
Tried 1.13.11.9rc2 still crashing ever, so often but without any warning even in light mode silly

**Comment by skrashevich** [comment]
> Tried 1.13.11.9rc2 still crashing ever, so often but without any warning even in light mode silly

Please, create issue about this problem. I don’t know about crashes in this version
